name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    defaults:
        run:
          shell: bash

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: 5.x
    
      - name: Execute GitVersion
        id: gitVersion
        uses: gittools/actions/gitversion/execute@v0.11.0

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          major_name="v${{ steps.gitVersion.outputs.Major }}"
          minor_name="v${{ steps.gitVersion.outputs.Major }}.${{ steps.gitVersion.outputs.Minor }}"
          patch_name="v${{ steps.gitVersion.outputs.SemVer }}"

          if gh release view "$major_name" &>/dev/null; then
            gh release delete "$major_name" --cleanup-tag

            should_sleep=true
          fi

          if gh release view "$minor_name" &>/dev/null; then
            gh release delete "$minor_name" --cleanup-tag

            should_sleep=true
            fi
            
          if [ "$should_sleep" = true ] ; then
            sleep 5 # Reusing tag before fully deleted causes release to be saved as draft: https://github.com/cli/cli/issues/8458
          fi

          gh release create "$major_name" --title "$major_name" --repo "${{ github.repository }}"
          gh release create "$minor_name" --title "$minor_name" --repo "${{ github.repository }}"
          gh release create "$patch_name" --title "$patch_name" --repo "${{ github.repository }}"