name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    defaults:
        run:
          shell: bash

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: 5.x
    
      - name: Execute GitVersion
        id: gitVersion
        uses: gittools/actions/gitversion/execute@v0.11.0

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.gitVersion.outputs.SemVer }}" --title "v${{ steps.gitVersion.outputs.SemVer }}" --repo "${{ github.repository }}"

          if gh release view "v${{ steps.gitVersion.outputs.Major }}" &>/dev/null; then
            gh release delete "v${{ steps.gitVersion.outputs.Major }}" --cleanup-tag

            sleep 5 # Reusing tag before fully deleted causes release to be saved as draft: https://github.com/cli/cli/issues/8458
          fi

          gh release create "v${{ steps.gitVersion.outputs.Major }}" --title "v${{ steps.gitVersion.outputs.Major }}" --repo "${{ github.repository }}"